### ISSUE TITLE
Running Bruno for conversion give me an internal crash in the tool.

### ISSUE THREAD

**Issue by shailesh-mota** [josem/bruno#1]
Crash : ```error: undefined method `[]' for nil:NilClass```

Ruby version : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
Mac : macOS Sierra Version 10.12.3
gem -v : 2.6.8

gem installed bruno and then run this command : ``` bruno convert --in Localizable.strings --out strings.xml```

**Comment by josem** [comment]
Hi @shailesh-mota!

Thanks for using Bruno and reporting this issue :)

To be honest it's been a while since I updated this project and for now it only supports 2.1 and previous versions of Ruby. 

My plan is to migrate this tool to another technology so I can have binaries and users don't need to worry about dependencies or installing Ruby. 

I'll keep you posted!
